name: Deploy Strapi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            set -e
            
            # Corrige problema de segurança do Git
            git config --global --add safe.directory /VemNenem-Backend
            
            cd /VemNenem-Backend
            
            # Verifica espaço em disco antes de continuar
            echo "Verificando espaço em disco..."
            df -h /
            
            # Limpa caches antes do deploy
            yarn cache clean
            rm -rf node_modules/.cache
            
            # Atualiza o código
            git pull origin main
            
            # Instala dependências
            yarn install
            
            # Limpa builds anteriores
            rm -rf .cache build dist
            
            # Build do Strapi
            NODE_ENV=production yarn build
            
            # Reinicia a aplicação
            pm2 restart vem-nenem || pm2 start yarn --name "vem-nenem" -- start
            
            echo "Deploy realizado com sucesso!"
          EOF