name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --ignore-engines

      - name: Build project
        run: yarn build
        env:
          NODE_ENV: production

      - name: Run tests (if available)
        run: yarn test || echo "No tests found"
        continue-on-error: true

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.USER }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh root@${{ secrets.USER }} << 'EOF'
            cd /VemNenem-Backend || exit 1
            git pull origin main || git pull origin master
            yarn install --ignore-engines
            yarn build
            pm2 restart vem-nenem || pm2 start yarn --name vem-nenem -- start
          EOF

      - name: Cleanup
        if: always()
        run: rm -rf ~/.ssh/id_rsa