name: CI

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Copy to Digital Ocean
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_KEY  }}
          source: ".,!node_modules"
          target: '/VemNenem-Backend'

      - name: Restart application
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_KEY  }}
          script: |
            cd /VemNenem-Backend
            npm install --production
            pm2 restart all