name: CI
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Copy code to Digital Ocean
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_KEY }}
          source: '.,!node_modules,!build,!.cache'
          target: '/VemNenem-Backend'
      
      - name: Deploy on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: root
          port: 22
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /VemNenem-Backend
            
            # Limpa builds antigos
            rm -rf build .cache
            
            # Instala TODAS as dependências (incluindo dev)
            yarn install --frozen-lockfile
            
            # Builda o admin
            NODE_ENV=production yarn build
            
            # limpa devDependencies
            yarn install --production --frozen-lockfile
            
            # Reinicia o PM2
            pm2 restart vem-nenem || pm2 start yarn --name "vem-nenem" -- start