name: Deploy Strapi

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USER }}@${{ secrets.HOST }} << 'EOF'
            cd /VemNenem-Backend
            git pull origin main
            
            # Instalar dependências (incluindo dev para o build)
            npm install
            
            # Build com limite de memória
            rm -rf .cache
            rm -rf build
            rm -rf dist
            NODE_OPTIONS="--max-old-space-size=1536" npm run build
            
            # Reiniciar PM2
            pm2 restart vem-nenem
            
            # Ver se está rodando
            pm2 list
          EOF